CREATE TABLE client (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    create_date TIMESTAMP DEFAULT NOW()
);

INSERT INTO client (name, email) VALUES ('PERILLO', 'PERILLO@GMAIL.COM');